blog/views/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app
from flask_login import (
    LoginManager,
    current_user,
    login_user,
    logout_user,
    login_required,
)

from sqlalchemy.exc import IntegrityError
from werkzeug.exceptions import NotFound

from blog.models.user import UserModel
from blog.models import db
from blog.forms.user import RegistrationForm, LoginForm

auth_app = Blueprint("auth_app", __name__)

login_manager = LoginManager()
login_manager.login_view = "auth_app.login"


@login_manager.user_loader
def load_user(user_id):
    return UserModel.query.filter_by(id=user_id).one_or_none()


@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for("auth_app.login"))


@auth_app.route("/login/", methods=["GET", "POST"], endpoint="login")
def login():
    if current_user.is_authenticated:
        return redirect("index")

    form = LoginForm(request.form)

    if request.method == "POST" and form.validate_on_submit():
        user = UserModel.query.filter_by(username=form.username.data).one_or_none()
        if user is None:
            return render_template("auth/login.html", form=form, error="username doesn't exist")
        if not user.validate_password(form.password.data):
            return render_template("auth/login.html", form=form, error="invalid username or password")

        login_user(user)
        return redirect(url_for("index"))

    return render_template("auth/login.html", form=form)


@auth_app.route("/login-as/", methods=["GET", "POST"], endpoint="login-as")
def login_as():
    if not (current_user.is_authenticated and current_user.is_staff):
        # non-admin users should not know about this feature
        raise NotFound


@auth_app.route("/logout/", endpoint="logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("index"))


@auth_app.route("/register/", methods=["GET", "POST"], endpoint="register")
def register():
    if current_user.is_authenticated:
        return redirect("index")

    error = None
    form = RegistrationForm(request.form)
    if request.method == "POST" and form.validate_on_submit():
        if UserModel.query.filter_by(username=form.username.data).count():
            form.username.errors.append("username already exists!")
            return render_template("auth/register.html", form=form)

        if UserModel.query.filter_by(email=form.email.data).count():
            form.email.errors.append("email already exists!")
            return render_template("auth/register.html", form=form)

        user = UserModel(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            username=form.username.data,
            email=form.email.data,
            is_staff=False,
        )
        user.password = form.password.data
        db.session.add(user)
        try:
            db.session.commit()
        except IntegrityError:
            current_app.logger.exception("Could not create user!")
            error = "Could not create user!"
        else:
            current_app.logger.info("Created user %s", user)
            login_user(user)
            return redirect(url_for("index"))
    return render_template("auth/register.html", form=form, error=error)


__all__ = [
    "login_manager",
    "auth_app",
]

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% include "css_include.html" %}
    <title>
      {% block title %}
        __TITLE__
      {% endblock title %}
    </title>
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
  </head>
  <body>
    {% block nav %}
      {% include "navbar.html" %}
    {% endblock nav %}
    {% block content %}
      __CONTENT__
    {% endblock content %}
    {% block footer %}
      __FOOTER__
    {% endblock footer %}
  </body>
</html>

blog/templates/css_include.html
<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
      rel="stylesheet"/>

blog/templates/index.html
{% extends "base.html" %}
{% block title %}
  Index Page
{% endblock title %}
{% block content %}
  <h1>
    Hello
    {% if current_user.is_authenticated %}
      {{ current_user.username }} !!!
    {% else %}
    !!!
    {% endif %}
  </h1>
{% endblock content %}
{% block footer %}
{% endblock footer %}

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('index')}}">BLOG</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('users_app.list')}}">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('authors_app.list')}}">Authors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('articles_app.list')}}">Articles</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Administration
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

                        {% if current_user.is_authenticated %}
                        <li><a class="dropdown-item" href="{{ url_for('auth_app.logout') }}">Log out</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{{ url_for('auth_app.login') }}">Log in</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('auth_app.register') }}">Sign in</a></li>
                        {% endif %}

                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>